"""Add cascade delete to reviews

Revision ID: 282a548fab02
Revises: bf9421d73c4f
Create Date: 2024-11-27 15:24:03.026295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282a548fab02'
down_revision = 'bf9421d73c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_task_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_task_id_fkey', 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###
