"""Delete  cascade delete to reviews

Revision ID: f0d33c7d6295
Revises: 282a548fab02
Create Date: 2024-11-27 15:31:09.717871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d33c7d6295'
down_revision = '282a548fab02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_task_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_task_id_fkey', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
